/* ===== TRACK 2: RELATIVITY & THE COSMOS — DEEPENED REWRITES (sr, gr) ===== */

addModule({
  id: "sr", track: "relativity", order: 1,
  title: "Special relativity",
  fields: ["relativity"], readMins: 30,
  summary: "Two modest postulates dismantle universal time: simultaneity becomes relative, clocks and rulers disagree, spacetime replaces space and time, and mass turns out to be the invariant length of a four-vector.",
  lesson: `
    <h3>The big picture</h3>
    <p>Special relativity is the shortest route in physics from almost nothing to almost everything. Einstein's 1905 paper assumes two things, neither of them exotic, and extracts from them that clocks disagree, that rulers disagree, that the word "now" has no universal meaning, that mass and energy are the same quantity in different units, and that there is a speed no material object can reach. Nothing is smuggled in. The theory is usually introduced as a theory of light, which damages understanding: it is a theory about the <strong>structure of spacetime</strong>, and light matters only because it happens to travel at the invariant speed. Every other theory in physics must respect that structure.</p>

    <h3>Two postulates, and how much they cost</h3>
    <p>The first postulate is old and uncontroversial. <strong>The laws of physics take the same form in every inertial frame</strong>: no experiment inside a smoothly moving laboratory can reveal its velocity. Galileo made the point with butterflies in a sealed ship's cabin, and Newtonian mechanics obeys it exactly. The second is the one that breaks things. <strong>Light in vacuum travels at the same speed c for every inertial observer</strong>, whatever the motion of the source or the observer. Chase a beam at ninety-nine per cent of c and it still retreats from you at precisely c, not at one per cent of c.</p>
    <p>Both cannot hold in a Newtonian universe, because Newton assumes velocities simply add. Something must be surrendered, and Einstein surrendered the assumption nobody had noticed they were making: that a single universal time ticks for everyone. Give that up and the rest is algebra. The algebra itself — the Lorentz transformation, rapidity, relativistic velocity addition, and the historical road through Maxwell, Michelson and Morley, Lorentz and Poincar&eacute; — is worked through in the <em>Frames and transformations</em> module. This one is about what those equations mean.</p>

    <h3>Simultaneity goes first</h3>
    <p>Most courses teach time dilation first. That is the wrong order, because time dilation is a <em>consequence</em> of something more basic: the collapse of universal simultaneity. Take Einstein's own thought experiment. A long train runs down a straight track at high speed, and lightning strikes both ends at once, scorching marks into train and embankment alike. Anna stands on the embankment exactly midway between the two marks; Ben sits at the exact centre of the train.</p>
    <p>Light from the two strikes reaches Anna together. She is equidistant from both marks and light travels at c, so she concludes correctly that the strikes were <strong>simultaneous</strong>. Ben is moving toward the front strike and away from the rear one, so the front light reaches him first. Now apply the second postulate strictly: light travels at c for Ben too, and Ben is midway between the ends of his own train. Equal distances, equal speeds, unequal arrival times — only one conclusion is available to him. The front was struck <em>first</em>. Ben is not mistaken and is not compensating for anything; in his frame the strikes genuinely were not simultaneous.</p>
    <div class="callout"><b>Why this is the root of everything:</b> measuring a length is a statement about where the two ends of an object are <em>at the same time</em>, and comparing two clocks means asking what each reads <em>at the same time</em>. Observers who disagree about simultaneity must therefore disagree about lengths and clock readings. Length contraction and time dilation are not extra postulates bolted on; they are what disagreement over simultaneity looks like when you try to measure something.</div>

    <h3>Time dilation, from a light clock</h3>
    <p>The cleanest derivation needs nothing beyond Pythagoras. Build a clock from two parallel mirrors a distance L apart with a light pulse bouncing between them; one tick is a round trip, taking 2L/c in the clock's rest frame. Now watch that clock fly past you sideways at speed v. The pulse cannot travel straight up and down, because the mirrors move while it is in flight, so it takes a longer diagonal path — at exactly the same speed c, because that is the postulate. A longer path at the same speed takes longer.</p>
    <div class="eq">(c&middot;t/2)&sup2; = L&sup2; + (v&middot;t/2)&sup2;
      <span class="why">The diagonal leg of the light path is the hypotenuse of a right triangle whose vertical side is the mirror separation and whose horizontal side is how far the clock moved in half a tick. Solve for t and you get the rest tick multiplied by the Lorentz factor.</span></div>
    <div class="eq">&gamma; = 1 / &radic;(1 &minus; v&sup2;/c&sup2;)
      <span class="why">At everyday speeds gamma differs from one in about the twelfth decimal place and nothing appears to happen. As v approaches c it runs away to infinity: clocks nearly stop and lengths nearly vanish as judged from another frame.</span></div>
    <p>Nothing there used light except as a convenient carrier. Every clock in the moving frame must slow by the same factor, because if a light clock and a wristwatch drifted apart you would have an experiment that detects absolute motion, which the first postulate forbids. Chemistry, radioactive decay and biological ageing all slow together.</p>

    <h3>Length contraction, and the twins</h3>
    <p>The companion result is that an object of rest length L measures L/&gamma; along its direction of motion, and is unchanged across it. The classic muon experiment shows the two effects are one fact seen twice. Cosmic rays create muons high in the atmosphere; a muon lives about 2.2 microseconds and ought to decay long before reaching the ground, yet muons arrive in quantity. From the ground frame the muon's internal clock runs slow, so it survives the trip. From the muon's frame its clock is perfectly normal, but the atmosphere is rushing past contracted to a fraction of its thickness, so there is far less distance to cover. Same muons, same count, two descriptions.</p>
    <p>Which brings us to the twin paradox. One twin flies to a distant star at high speed and returns; the other stays home. Each sees the other's clock running slow while they separate, so why is the outcome not symmetric? The resolution needs no general relativity. <strong>The travelling twin is not in a single inertial frame.</strong> To come back she must turn around, and she can feel the turnaround with an accelerometer bolted to the floor. At that moment she changes inertial frame, and her judgement of which distant events count as "now" swings forward sharply — the stay-at-home clock jumps ahead in her accounting. The stay-at-home twin never accelerates and never makes that correction.</p>
    <p>The asymmetry is real and measurable, not bookkeeping. Both twins agree at the reunion about who is younger, because that is a single local comparison of two clocks at one event. Hafele and Keating flew caesium clocks around the world in both directions in 1971 and found offsets of hundreds of nanoseconds, matching the combined special- and general-relativistic prediction. Muons circulating in a CERN storage ring, which certainly accelerate, live longer by exactly gamma with no fudge factor.</p>

    <h3>Spacetime, the interval and proper time</h3>
    <p>Hermann Minkowski supplied the geometry in 1908: space and time are not separate stages but a single four-dimensional <strong>spacetime</strong>. Different observers slice it into "space" and "time" at different angles, like cutting a loaf on the diagonal, which is exactly why they disagree about durations and lengths. All of them agree on one combined measure, the <strong>spacetime interval</strong>:</p>
    <div class="eq">&Delta;s&sup2; = (c&Delta;t)&sup2; &minus; (&Delta;x)&sup2; &minus; (&Delta;y)&sup2; &minus; (&Delta;z)&sup2;
      <span class="why">The same number for every inertial observer. That minus sign is the whole difference between Minkowski geometry and ordinary Euclidean geometry, and it is what makes time different in kind from space rather than merely a fourth direction.</span></div>
    <p>The minus sign generates causal structure. If the interval between two events is timelike, one can influence the other and every observer agrees which came first. If it is spacelike, no signal can connect them and observers genuinely disagree about their order — which is harmless, precisely because neither can cause the other. If it is zero, only light connects them, and that boundary case sweeps out the <strong>light cone</strong> separating an event's causal past and future from the vast elsewhere it can neither affect nor learn about.</p>
    <p>Along a timelike path, the interval divided by c is the <strong>proper time</strong>, and this is the most useful quantity in the theory: it is what a clock carried along that path actually reads. Coordinate time is an accounting convention that depends on your frame; proper time is a physical measurement everyone agrees on. Straight worldlines maximise proper time between two events, which is the geometric statement of the twin paradox — the inertial twin takes the longest-in-time route.</p>

    <h3>Four-vectors: the natural language</h3>
    <p>Once you accept the geometry, the sensible way to write physics is in objects that transform cleanly under Lorentz transformations, called <strong>four-vectors</strong>. The <strong>four-position</strong> gathers the time and space coordinates of an event into one object. The <strong>four-velocity</strong> is the rate of change of four-position with respect to <em>proper time</em> rather than coordinate time, and that choice is the crucial one, because proper time is invariant. Multiply the four-velocity by the rest mass and you have the <strong>four-momentum</strong>, whose time component is energy divided by c and whose space components are the relativistic momentum.</p>
    <p>Every four-vector has an invariant length, computed with the same minus signs as the interval. For four-momentum that length has a striking meaning:</p>
    <div class="eq">(E/c)&sup2; &minus; |p|&sup2; = (mc)&sup2;
      <span class="why">The invariant length of the four-momentum is the rest mass. Energy and momentum each depend on who is looking; this combination does not. Mass is not a quantity of stuff but a geometric invariant of a four-vector.</span></div>
    <p>This is why four-vectors earn their keep. Conservation of energy and conservation of momentum stop being two laws and become one — four-momentum is conserved, and different observers merely slice that single law into time and space parts differently. Particle physicists work almost entirely in these terms, because the invariant mass of a system is what survives translation between the laboratory and centre-of-mass frames.</p>

    <h3>What E = mc&sup2; actually says</h3>
    <p>Rearranging that invariant gives the relation that deserves to be the famous one:</p>
    <div class="eq">E&sup2; = (pc)&sup2; + (mc&sup2;)&sup2;
      <span class="why">The full energy-momentum relation. Set momentum to zero and you recover E = mc squared, the rest energy. Set mass to zero and you get E = pc, correctly giving massless particles such as photons real energy and momentum despite having no mass at all.</span></div>
    <p>E = mc&sup2; is therefore the special case for a body at rest, and what it says precisely is that <strong>a body at rest has an energy proportional to its mass</strong>, with c&sup2; as the exchange rate. It is not an alchemical conversion of mass into energy; mass <em>is</em> energy, already present, and nuclear reactions release a fraction of it by rearranging binding. Fusing hydrogen to helium liberates about 0.7 per cent of the mass, which is enough to run the Sun.</p>
    <div class="callout"><b>A deprecated way of speaking:</b> older texts say mass "increases with speed", defining a relativistic mass equal to gamma times m. It gives right answers in simple cases and confuses almost everyone, since it implies a fast electron might collapse into a black hole in some frames. Modern practice is that <em>mass is invariant</em> — the rest mass, full stop — and that energy and momentum are what grow. The speed limit is then stated correctly: accelerating a massive body to c needs infinite energy because gamma diverges, not because anything gets heavier.</div>

    <h3>Doppler, aberration and the record</h3>
    <p>Two observable effects complete the picture. The <strong>relativistic Doppler shift</strong> combines the familiar classical shift from approach or recession with time dilation of the source's own oscillation. That extra factor produces something classically impossible: a <strong>transverse Doppler shift</strong>, a pure redshift seen even when the source moves exactly perpendicular to the line of sight and its distance is momentarily unchanging. Ives and Stilwell measured it in 1938, and it remains one of the cleanest direct confirmations of time dilation. <strong>Relativistic aberration</strong> is the companion effect on direction: at high speed the apparent positions of stars crowd toward the direction of travel, and radiation from a fast source is beamed forward into a cone of angle roughly 1/&gamma;. That is why the jets of active galaxies look so absurdly bright when aimed at us.</p>
    <p>The evidence is not thin. Atmospheric muons reach the ground; storage-ring muons live longer by gamma; accelerators would miss every target if their magnets were designed on Newtonian dynamics; modern ion-storage-ring versions of the Ives-Stilwell test confirm time dilation to extraordinary precision; and GPS satellites, moving fast and sitting high, would accumulate navigation errors of kilometres per day without relativistic correction. Every particle-physics result of the last seventy years is a relativity test that passed.</p>
    <p>The closing point is the one to carry away. Special relativity is not a theory about light, or about fast rockets, or about strange things at the edge of the possible. It is a constraint on <em>the shape of spacetime itself</em>, and every other theory must be written to respect it. Quantum mechanics had to be rebuilt as quantum field theory to comply, and that requirement alone forces antimatter, spin, and the link between spin and statistics. Relativity is not one theory among many; it is the frame the others hang in.</p>
  `,
  keyIdeas: [
    "The speed of light is identical for all observers, regardless of their motion.",
    "To keep c constant, moving clocks run slow (time dilation) and moving lengths contract.",
    "Simultaneity is relative: there is no universal 'now' shared across the universe.",
    "Space and time are one four-dimensional spacetime; observers agree on the invariant spacetime interval.",
    "E = mc² means mass and energy are interchangeable; a little mass is a lot of energy.",
    "Nothing with mass or information can reach the speed of light.",
    "Proper time is what a clock physically reads along its own worldline, and the twin paradox resolves because only the travelling twin accelerates and changes inertial frame — a real, measured asymmetry.",
    "Four-momentum unifies energy and momentum into one conserved four-vector whose invariant length is the rest mass, so E squared equals (pc) squared plus (mc squared) squared is the fundamental relation and handles massless particles correctly."
  ],
  talk: {
    oneliners: [
      "Special relativity is one stubborn fact taken seriously: light's speed is the same for everyone, so time and space have to bend to allow it.",
      "Moving clocks run slow and moving rulers shrink — not as an illusion, but really; GPS has to correct for it.",
      "The biggest shock isn't time dilation, it's that 'now' is relative — simultaneous events for me aren't simultaneous for you.",
      "E = mc² just says mass is concentrated energy, and c² is the enormous exchange rate.",
      "The twin paradox isn't a paradox: only one twin turns around, feels it, and swaps inertial frames, and that asymmetry is measurable."
    ],
    myths: [
      { m: "Relativity says 'everything is relative'.", t: "Quite the opposite — it's built on absolutes: the speed of light and the spacetime interval are the same for everyone." },
      { m: "Time dilation is just an illusion or a clock malfunction.", t: "It is physically real and measured routinely, from atmospheric muons to atomic clocks on aircraft and satellites." },
      { m: "Nothing can ever travel faster than light, full stop.", t: "Nothing carrying mass or information can; abstract things like the expansion of space or a laser spot's sweep can exceed c without breaking causality." },
      { m: "Mass increases as you approach the speed of light.", t: "That is deprecated language. Mass is the invariant length of the four-momentum and never changes; it is the energy and momentum that grow without bound as gamma diverges." }
    ],
    terms: [
      { term: "Inertial frame", def: "A non-accelerating point of view; all such frames are physically equivalent." },
      { term: "Lorentz factor (γ)", def: "1/√(1−v²/c²); the stretch/shrink factor for time and length at speed v." },
      { term: "Time dilation", def: "A moving clock runs slow relative to a stationary observer." },
      { term: "Length contraction", def: "A moving object is shortened along its direction of motion." },
      { term: "Simultaneity (relativity of)", def: "Whether two separated events happen 'at the same time' depends on the observer." },
      { term: "Spacetime interval", def: "The observer-independent measure combining time and space, with a relative minus sign." },
      { term: "Proper time", def: "The interval measured along a worldline; what a clock carried on that path actually reads, and an invariant everyone agrees on." },
      { term: "Four-momentum", def: "The four-vector combining energy and momentum; its invariant length is the rest mass, giving E squared equals (pc) squared plus (mc squared) squared." }
    ]
  },
  test: [
    { q: "What are the two postulates of special relativity?", a: "1) The laws of physics are the same in all inertial (non-accelerating) frames. 2) The speed of light in vacuum is the same for all inertial observers, independent of the motion of source or observer." },
    { q: "Why do moving clocks run slow?", a: "Because the speed of light is fixed for everyone, keeping c constant across frames in relative motion forces time and distance to transform. The result is that a clock moving relative to you ticks slower by the Lorentz factor γ." },
    { q: "What does the relativity of simultaneity mean?", a: "Two events judged simultaneous by one observer will generally not be simultaneous for another observer moving relative to the first. There is no universal 'now' across space." },
    { q: "What is the physical content of E = mc²?", a: "Mass and energy are equivalent; mass is an extremely dense store of energy, with the conversion factor c². It underlies stellar fusion and nuclear energy, and implies massive objects cannot reach light speed." },
    { q: "Resolve the twin paradox, and say why the four-momentum picture matters.", a: "The situation is not symmetric: the travelling twin must turn around, feels the acceleration, and changes inertial frame, so her judgement of which distant events are simultaneous swings forward and the stay-at-home clock jumps ahead in her accounting. The stay-at-home twin never accelerates and ages more, and the difference is a single local comparison at the reunion, confirmed by flown atomic clocks and storage-ring muons. Four-momentum matters because it packages energy and momentum into one conserved object whose invariant length is the rest mass, so E squared equals (pc) squared plus (mc squared) squared is more fundamental than E = mc squared and correctly gives massless photons energy E = pc." }
  ],
  resources: [
    { name: "David Tong — Dynamics and Relativity", desc: "Free notes; the special-relativity sections are excellent.", url: "https://www.damtp.cam.ac.uk/user/tong/relativity.html", type: "notes", icon: "📄" },
    { name: "MIT 8.033 — Relativity", desc: "Full undergraduate course on special (and intro general) relativity.", url: "https://ocw.mit.edu/courses/8-033-relativity-fall-2006/", type: "course", icon: "🎓" },
    { name: "Susskind — Special Relativity & Classical Field Theory", desc: "Full lecture course with the spacetime view.", url: "https://theoreticalminimum.com/courses", type: "video", icon: "▶️" },
    { name: "Feynman Lectures Vol. I (Ch. 15–17)", desc: "Beautifully clear chapters on relativity, spacetime and relativistic energy and momentum.", url: "https://www.feynmanlectures.caltech.edu/", type: "book", icon: "📚" },
    { name: "Sean Carroll — Lecture Notes on General Relativity (Ch. 1)", desc: "Chapter 1 is a first-class treatment of Minkowski geometry, four-vectors and tensors.", url: "https://arxiv.org/abs/gr-qc/9712019", type: "notes", icon: "📄" }
  ]
});

addModule({
  id: "gr", track: "relativity", order: 2,
  title: "General relativity",
  fields: ["relativity"], readMins: 32,
  summary: "Gravity is not a force but the curvature of spacetime. The equivalence principle forces the geometric picture, the field equations tie curvature to energy and momentum, and the theory predicts its own breakdown at singularities.",
  lesson: `
    <h3>The big picture</h3>
    <p>General relativity, completed in November 1915 after eight years of struggle, is Einstein's masterpiece and by common consent the most beautiful theory in physics. Its central claim overturns two and a half centuries of Newton: <strong>gravity is not a force</strong>. It is the curvature of spacetime. Matter and energy warp the geometry around them, and everything else follows the straightest paths available through that warped geometry. What we feel as weight is not a pull but the ground pushing us off the straight path we would otherwise take. Special relativity told us spacetime has a fixed geometry all physics must respect; general relativity's move is to make that geometry <em>dynamical</em> — a participant in physics rather than a stage for it.</p>

    <h3>The happiest thought</h3>
    <p>Einstein called it the happiest thought of his life: a person in free fall does not feel their own weight. That observation is the seed of the theory, and it splits into two statements of increasing strength.</p>
    <p>The <strong>weak equivalence principle</strong> is the ancient observation, tested by Galileo and refined ever since, that all bodies fall with the same acceleration whatever their mass or composition. In Newtonian terms this is an odd coincidence: the mass in F = ma has no obvious reason to equal the mass in the law of gravitation, yet experiment says they agree to better than one part in 10&#185;&#8309;. The <strong>strong equivalence principle</strong> promotes the coincidence to a principle: in a small enough region, the results of <em>all</em> experiments in a freely falling laboratory — optics, nuclear physics, everything, not just falling bodies — are identical to those in an inertial laboratory in deep space with no gravity at all.</p>
    <p>The elevator thought experiment makes this concrete. Seal yourself in a windowless lift. If you and everything else float, you cannot tell whether you are adrift in empty space or plummeting down a shaft. If you stand on the floor at a comfortable weight, you cannot tell whether you are parked on Earth or being towed through deep space at 9.8 metres per second squared. Now shine a torch horizontally across the accelerating lift: the beam strikes the far wall slightly below the height it left, because the lift rose during the flight time. By the principle, the same must happen in a gravitational field, so <strong>light must bend in gravity</strong>. Einstein had that conclusion in 1907, eight years before he had the equations.</p>

    <h3>Tides: what separates real gravity from acceleration</h3>
    <p>The word doing the work above is <em>locally</em>. Equivalence is exact only over a region small enough that the field is uniform across it, and no real field is. Release two balls side by side in a lift falling toward Earth and they drift slowly <em>together</em>, because both fall toward the planet's centre and those directions are not quite parallel. Release two balls one above the other and they drift <em>apart</em>, because the lower one is pulled harder. In a rocket accelerating through empty space, neither happens.</p>
    <p>These <strong>tidal effects</strong> are the observable, frame-independent content of gravity, and they are what curvature means. No choice of coordinates removes them, which is precisely the signature of genuine curvature rather than an awkward map. Ocean tides are the same thing at planetary scale: the Moon does not lift the oceans, it pulls the near side harder than the centre and the centre harder than the far side, and the difference does the work.</p>
    <div class="callout"><b>The key move:</b> a freely falling body feels nothing, so free fall — not rest — is the natural, unforced state of motion. Free-falling objects travel in straight lines. It is spacetime that is curved, which makes those straight lines look, to us standing on a planet, like the arcs of falling stones and the ellipses of orbits.</div>

    <h3>The geometric turn</h3>
    <p>The straightest available path through a curved geometry is a <strong>geodesic</strong>, and gravitational motion reduces to one sentence: <em>free bodies follow timelike geodesics</em>. On a sphere the geodesics are great circles, which is why flights from London to Los Angeles arc north over Greenland though the map makes it look like a detour. In spacetime the same logic applies in four dimensions with a minus sign, and the geodesic is the path of <strong>maximum proper time</strong> between two events.</p>
    <p>This dissolves a very old question. The Moon is not being pulled and is not being held up by anything; it coasts freely along the straightest track available in the geometry the Earth's mass has made, and that track happens to close on itself. Its four-acceleration is zero. Meanwhile you, sitting still in a chair, <em>are</em> accelerating, because the chair continuously pushes you off the geodesic you would follow if the floor gave way. Newton's puzzle of action at a distance never arises, since nothing acts at a distance.</p>
    <p>One point catches most people out. For anything moving slowly compared with light, the dominant curvature is not that of space but the <strong>curvature of time</strong>. You fall toward the Earth mainly because clocks tick slightly slower closer to it, so the path of maximum proper time bends downward. The familiar rubber-sheet picture, with a bowling ball denting a trampoline, is a two-dimensional analogy of the wrong dimension: it shows curved space and quietly assumes the gravity it is supposed to explain.</p>

    <h3>The metric, and what curvature measures</h3>
    <p>All the geometry lives in one object, the <strong>metric tensor</strong>, whose job is elementary to state: it gives the interval between two nearby events from their coordinate separations.</p>
    <div class="eq">ds&sup2; = g<sub>&mu;&nu;</sub> dx<sup>&mu;</sup> dx<sup>&nu;</sup>
      <span class="why">Ten independent functions of position, one for each pair of the four coordinates. In flat spacetime they reduce to the plus and minus ones of Minkowski geometry; near a mass they vary from place to place, and that variation is the gravitational field. Every measurable quantity — distances, times, angles, light paths — is computed from them.</span></div>
    <p>This is also why the theory is written in tensors: physics must not depend on the arbitrary coordinate labels you laid down, so the equations are built from objects that transform properly under any smooth relabelling. Two derived objects then do the heavy lifting. The <strong>Christoffel symbols</strong> tell you how to compare vectors at neighbouring points — how much a vector's components must change simply to keep it pointing the same way as you slide it along. They encode the apparent gravitational acceleration, and being partly coordinate artefacts, they can always be made zero at any single point. That is the equivalence principle in mathematical dress: locally, you can always fall into a frame where gravity vanishes.</p>
    <p>What you cannot make vanish is the <strong>Riemann curvature tensor</strong>. It measures the failure of parallel transport to commute: carry a vector around a small closed loop, keeping it as parallel as you can, and in curved spacetime it returns rotated. More physically, Riemann measures <em>geodesic deviation</em> — the rate at which two initially parallel free-falling paths converge or diverge. That is exactly the tidal effect above. If Riemann vanishes everywhere, spacetime is flat and any apparent gravity is a coordinate illusion; if it does not, the gravity is real and no coordinates will hide it.</p>

    <h3>The field equations</h3>
    <p>The theory then compresses into one line, which is really ten coupled non-linear partial differential equations:</p>
    <div class="eq">G<sub>&mu;&nu;</sub> + &Lambda;g<sub>&mu;&nu;</sub> = (8&pi;G/c&#8308;) T<sub>&mu;&nu;</sub>
      <span class="why">The left side is pure geometry: the Einstein tensor, a particular combination of the curvature that is automatically conserved, plus an optional cosmological constant term multiplying the metric. The right side is pure content: the stress-energy tensor, describing all matter, radiation, pressure and stress present. The constant in front is fixed by demanding that the equations reproduce Newtonian gravity in the weak, slow limit.</span></div>
    <p>John Wheeler's summary is unimprovable: <strong>spacetime tells matter how to move; matter tells spacetime how to curve</strong>. The two halves are not independent, which is what makes the equations so hard. Curvature depends on the matter, the matter's motion depends on the curvature, and gravitational energy itself gravitates — so the equations are non-linear and you cannot add two solutions together. Exact solutions are rare and precious, which is why the field runs largely on approximations and supercomputers.</p>

    <h3>What gravitates, and the classic tests</h3>
    <p>The right-hand side quietly corrects Newton. The source of gravity is not mass but the <strong>stress-energy tensor</strong>, whose components include energy density, momentum density and, importantly, <strong>pressure and stress</strong>. Pressure gravitates. A hot gas weighs more than the same gas cold, a box of light has weight though photons are massless, and inside a collapsing star the pressure resisting collapse itself adds to the gravity driving it — one reason collapse becomes unstoppable. It is equally why a negative-pressure component behaves repulsively and can accelerate cosmic expansion.</p>
    <ul>
      <li><strong>Mercury's perihelion.</strong> Mercury's orbital ellipse slowly rotates. Newtonian perturbations from the other planets account for nearly all of it, but 43 arcseconds per century stayed stubbornly unexplained for half a century, prompting astronomers to postulate an unseen planet, Vulcan. Einstein's theory produced the 43 arcseconds with no free parameters. He said it gave him heart palpitations. This was a prediction of an <em>existing</em> anomaly, not a retrofit.</li>
      <li><strong>Light bending, and 1919.</strong> Newtonian corpuscles plus the equivalence principle alone give a deflection of 0.87 arcseconds at the Sun's limb. Full general relativity gives exactly twice that, 1.75 arcseconds, because for something moving at c the curvature of space contributes as much as the curvature of time. Eddington's eclipse expeditions to Pr&iacute;ncipe and Sobral in May 1919 found the larger value and made Einstein famous overnight. The data were noisier than the headlines suggested, but radio interferometry and astrometry have since confirmed the prediction to better than a hundredth of a per cent, and gravitational lensing is now a routine tool for weighing clusters and mapping dark matter.</li>
      <li><strong>Gravitational redshift.</strong> Light climbing out of a gravitational well loses energy and reddens. Pound and Rebka measured it in 1959 over the 22.5 metres of a Harvard tower, using the M&ouml;ssbauer effect to detect a fractional frequency shift of about two parts in 10&#185;&#8309; — a beautifully small measurement, and a direct test of the equivalence principle.</li>
      <li><strong>The Shapiro delay.</strong> Irwin Shapiro noted in 1964 that a radar signal passing near the Sun takes measurably longer to return, because it crosses a region where clocks run slow: roughly 200 microseconds for a grazing round trip. Confirmed with Venus, then the Viking landers, and now measured to parts in 10&#8309; with the Cassini spacecraft.</li>
    </ul>

    <h3>Time dilation in your pocket, frame dragging, and waves</h3>
    <p>Gravitational time dilation is not exotic. Clocks deeper in a potential well genuinely run slow; your head ages fractionally faster than your feet, and optical clocks now resolve the difference over a height change of centimetres. The practical consequence sits in every phone. GPS satellites at 20,200 km face two competing effects: their orbital speed makes their clocks lose about 7 microseconds a day, while the weaker gravity at altitude makes them gain about 45. The net 38 microseconds a day corresponds to a positioning error of roughly 10 km per day if uncorrected, so satellite clocks are deliberately detuned before launch.</p>
    <p><strong>Frame dragging</strong> has no Newtonian analogue at all: a rotating mass drags the spacetime around it into rotation, so an orbiting gyroscope slowly precesses and even a freely falling observer picks up angular motion. Gravity Probe B measured the effect around the Earth in 2011, some 37 milliarcseconds per year, and the LAGEOS satellites confirmed it independently.</p>
    <p><strong>Gravitational waves</strong> are ripples in the metric itself, travelling at c. Because there is no negative gravitational charge there is no dipole radiation as in electromagnetism; the leading term is <strong>quadrupole</strong>, requiring a changing quadrupole moment, so a spherically symmetric pulsation radiates nothing at all. The waves are <em>transverse</em>, stretching space along one axis while squeezing the perpendicular one and then reversing, in two polarisations conventionally called plus and cross. Einstein predicted them in 1916, doubted them in 1936, and was right in the end: Hulse and Taylor watched a binary pulsar's orbit decay at exactly the predicted rate, and LIGO caught a merger directly on 14 September 2015 at a strain of about one part in 10&sup2;&sup1; — a length change smaller than a proton across a four-kilometre arm.</p>

    <h3>Cosmology, and where the theory ends</h3>
    <p>Applied to the universe as a whole, the field equations refuse to allow a static cosmos: it must expand or contract. Einstein, believing in 1917 that the universe was static, added the cosmological constant &Lambda; to hold it still. Hubble's discovery of expansion in 1929 made the fix unnecessary and Einstein dropped it. The story that he called it his "biggest blunder" reaches us second-hand through George Gamow and is <em>probably apocryphal</em>; there is no record of Einstein saying it. The joke is on everyone involved, because the accelerating expansion found in 1998 put the cosmological constant straight back at the centre of cosmology as the leading description of dark energy.</p>
    <p>The theory also marks out where it stops. The Penrose-Hawking singularity theorems show that under very general and physically reasonable conditions, gravitational collapse and the cosmological past both lead inevitably to <strong>singularities</strong> — places where curvature invariants diverge, geodesics simply end, and prediction ceases. This is not a quirk of one solution but a structural result: general relativity predicts its own breakdown. At the centre of a black hole and at the first instant of the Big Bang the classical description must give way to something quantum, and no complete theory of quantum gravity exists.</p>
    <div class="callout"><b>Where to go next:</b> event horizons, the Schwarzschild and Kerr geometries, what infall actually looks like and the thermodynamics of horizons are covered properly in the <em>black holes</em> track. The breakdown at the Planck scale, the clash between a dynamical metric and quantum field theory, and the candidate resolutions are covered in the <em>quantum gravity</em> track. This module deliberately stops at the boundary of both.</div>
  `,
  keyIdeas: [
    "Gravity is not a force but the curvature of spacetime caused by mass and energy.",
    "The equivalence principle: gravity and acceleration are locally indistinguishable, and free fall feels weightless.",
    "The Einstein field equations link spacetime curvature to the energy and momentum present.",
    "GR predicts light bending, gravitational time dilation, black holes and gravitational waves — all confirmed.",
    "Matter tells spacetime how to curve; spacetime tells matter how to move.",
    "GR breaks down at singularities, where it must give way to an unknown theory of quantum gravity.",
    "Tidal effects are the frame-independent content of gravity and cannot be transformed away, which is exactly what the Riemann curvature tensor measures; the metric encodes all geometry, while the Christoffel symbols, which can always be zeroed at a point, encode the apparent gravitational acceleration.",
    "The source of gravity is the full stress-energy tensor, so pressure and energy gravitate as well as mass, and gravitational waves are transverse quadrupole ripples in the metric because gravity has no dipole radiation."
  ],
  talk: {
    oneliners: [
      "General relativity's one big idea: gravity isn't a force, it's the shape of spacetime — mass bends it, and things just follow the bends.",
      "The equivalence principle is the seed: standing in gravity feels exactly like accelerating in a rocket, so gravity must be geometry.",
      "You fall to Earth mainly because your path through time is curved, not because something is pulling you.",
      "Black holes and gravitational waves were pure predictions of the maths, confirmed decades later by imaging and by LIGO.",
      "Acceleration and gravity are only the same locally — tides give real gravity away, and tides are precisely what curvature means."
    ],
    myths: [
      { m: "In orbit there's no gravity, so astronauts float.", t: "There's nearly full gravity in orbit; they float because they're in continuous free fall, which the equivalence principle says feels weightless." },
      { m: "The rubber-sheet picture is literally how gravity works.", t: "It's a 2D analogy; real gravity is 4D spacetime curvature, and for slow objects it's the curvature of time that matters most." },
      { m: "Nothing can escape a black hole because gravity 'pulls infinitely hard'.", t: "Inside the event horizon, all future-pointing paths lead inward; it's the geometry of spacetime, not an infinite pulling force." },
      { m: "Einstein called the cosmological constant his biggest blunder.", t: "The quote reaches us only second-hand through Gamow and is probably apocryphal. In any case the constant is back, as the leading description of dark energy since 1998." }
    ],
    terms: [
      { term: "Equivalence principle", def: "Gravity and acceleration are locally indistinguishable." },
      { term: "Geodesic", def: "The straightest possible path through curved spacetime; what free-falling objects follow." },
      { term: "Spacetime curvature", def: "The bending of spacetime geometry by energy and momentum." },
      { term: "Event horizon", def: "The boundary of a black hole from within which nothing can escape." },
      { term: "Gravitational waves", def: "Ripples in spacetime from accelerating masses, detected by LIGO." },
      { term: "Singularity", def: "A point of infinite curvature where general relativity breaks down." },
      { term: "Metric tensor", def: "The object giving the interval between nearby events; it encodes all the geometry, and its variation from place to place is the gravitational field." },
      { term: "Riemann curvature tensor", def: "The measure of genuine curvature, equal to the rate at which neighbouring geodesics converge or diverge; it cannot be transformed away by any choice of coordinates." }
    ]
  },
  test: [
    { q: "What is the core idea of general relativity?", a: "Gravity is not a force but the curvature of four-dimensional spacetime. Mass and energy curve spacetime, and objects follow the straightest available paths (geodesics) through that curved geometry." },
    { q: "State the equivalence principle and why it matters.", a: "Locally, the effects of gravity are indistinguishable from acceleration (and free fall is indistinguishable from being in gravity-free space). This implies gravity is not a conventional force but a feature of spacetime geometry — the foundation of GR." },
    { q: "Name three confirmed predictions of GR.", a: "Any three of: the bending of starlight by the Sun (1919 eclipse), gravitational time dilation (used in GPS), the anomalous precession of Mercury, black holes (imaged in 2019), and gravitational waves (LIGO, 2015)." },
    { q: "Where and why does general relativity break down?", a: "At singularities — the centres of black holes and the initial Big Bang — where curvature becomes infinite. There the classical theory fails and a quantum theory of gravity, which we do not yet have, is needed." },
    { q: "What distinguishes real gravity from mere acceleration, and what sources it?", a: "Tidal effects. Equivalence holds only locally; over any finite region a real gravitational field makes neighbouring free-falling paths converge or diverge, and no change of coordinates removes that. This geodesic deviation is exactly what the Riemann curvature tensor measures. The source on the right-hand side of the field equations is the full stress-energy tensor, so energy, momentum, pressure and stress all gravitate, not just mass." }
  ],
  resources: [
    { name: "David Tong — General Relativity", desc: "Graduate-level free notes; rigorous and clear.", url: "https://www.damtp.cam.ac.uk/user/tong/gr.html", type: "notes", icon: "📄" },
    { name: "Sean Carroll — Lecture Notes on General Relativity", desc: "The classic free notes that became his textbook; the best route into tensors and curvature.", url: "https://arxiv.org/abs/gr-qc/9712019", type: "notes", icon: "📄" },
    { name: "MIT 8.962 — General Relativity", desc: "Full graduate course with lecture notes and problem sets.", url: "https://ocw.mit.edu/courses/8-962-general-relativity-spring-2020/", type: "course", icon: "🎓" },
    { name: "Susskind — General Relativity", desc: "Accessible lecture course in the Theoretical Minimum series.", url: "https://theoreticalminimum.com/courses", type: "video", icon: "▶️" },
    { name: "Feynman Lectures Vol. II (Ch. 42, Curved Space)", desc: "Feynman's own conceptual account of curvature and gravitation.", url: "https://www.feynmanlectures.caltech.edu/", type: "book", icon: "📚" }
  ]
});
